/*
 * File: app/store/MyJsonTreeStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyWorkFlowApp.store.MyJsonStore', {
    extend: 'Ext.data.Store',
    requires: [
        'MyWorkFlowApp.model.MyModel'
    ],

    constructor: function(cfg) {
//        debugger;
        var me = this;
        cfg = cfg || {};


        me.callParent([Ext.apply({
//            autoLoad: true,
//            autoSync: true,

            storeId: 'MyJsonStore',
            model: 'MyWorkFlowApp.model.MyModel',

            sorters:[{property:'calc_priority', direction: 'DESC'}],
//            sorters:[{property:'priority', direction: 'DESC'}],

//            defaultRootProperty: 'children',
/*
            root: {
                    items: [
                        {
                            text: 'Drinks',
                            items: [
                                {
                                    text: 'Water',
                                    items: [
                                        { text: 'Still', leaf: true },
                                        { text: 'Sparkling', leaf: true }
                                    ]
                                },
                                { text: 'Soda', leaf: true }
                            ]
                        },
                        {
                            text: 'Snacks',
                            items: [
                                { text: 'Nuts', leaf: true },
                                { text: 'Pretzels', leaf: true },
                                { text: 'Wasabi Peas', leaf: true  }
                            ]
                        }
                    ]
                },
*/
            proxyLOCAL: {
                type: 'localstorage',
                id  : 'myjsontreedata',
                batchActions: false,
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});